# Generated by Django 5.2.13 on 2026-04-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='cetegoria',
            new_name='categoria',
        ),
    ]
