# Generated by Django 5.2.13 on 2026-04-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
    ]
